### ISSUE TITLE
REL: Change the name

### ISSUE THREAD

**Issue by HaoZeke** [d-SEAMS/PydSEAMSlib#12]
Just realized from https://github.com/seldon-code/pyseldonlib/issues/9 that we'll run into the same issue here as well, since I can see that `pyseams` is considered too close to `pyteams`.

![image](https://github.com/user-attachments/assets/e8e4b15e-efe3-4935-857d-7c0fa2ee48ff)

Unfortunately the same `..lib` approach won't work here because of 
![image](https://github.com/user-attachments/assets/d6a44a2f-0f2c-4b22-ae74-0a422b747ce4)

Will need another descriptive name, @RuhiRG @amritagos.

**Comment by RuhiRG** [comment]
What about `pydSEAMSlib`?
![image](https://github.com/user-attachments/assets/6dcbca23-0bad-4fe2-a162-c808b4b719cb)

**Comment by HaoZeke** [comment]
Works for me, changing the name now.
